window.DATA = window.DATA || {};
window.DATA['scheduler'] = {
  cat:"scheduling · coordination · reliability",
  title:"Design a distributed job scheduler (cron-at-scale)",
  blurb:"Users submit one-time and recurring jobs; the system runs each reliably at the right time, with retries, at massive scale — never lose a job, never silently drop an execution.",
  prompt:"Let's design a distributed job scheduler, think Apache Airflow or cron-at-scale. Users submit one-time jobs (run at time T) and recurring cron jobs (every 5 minutes, every midnight), and the system must execute each one reliably at the right moment, retry on failure, and keep working when nodes die. The interesting parts here are the distributed bits: durability, coordination so two schedulers don't double-fire, at-least-once execution plus idempotency, and clean failure handling. The scheduling math is not the point. Start with the high-level architecture and rough numbers, then we'll drill into components and I'll throw failures at you.",
  opening:"Let me frame it before drawing boxes.<br><br><strong>Functional:</strong> submit a one-time job to run at time T; submit a recurring cron job; execute jobs reliably at their scheduled time with automatic retries; and let users monitor a job's status and run history. <strong>Non-functional:</strong> the hard invariants are <strong>durability</strong> (a submitted job is never lost, even if a node dies the instant after submit) and <strong>at-least-once execution</strong> paired with <strong>idempotency</strong> so a job runs even across failures but a duplicate run is harmless. Execution should be <strong>timely</strong> (fired within a second or two of its due time) and the whole thing must be <strong>fault tolerant</strong> — a scheduler or worker dying can't stall the system.<br><br><strong>Back-of-envelope:</strong> say <strong>100M</strong> jobs registered, executions averaging <strong>10K/s</strong> steady-state, but wildly spiky — cron favors round times, so <strong>1M</strong> jobs can all be due at midnight in the same second. Job defs are small (a few KB), so storage is modest (~hundreds of GB); the pressure is the read pattern of finding due jobs cheaply and the write pattern of state transitions, not raw bytes.<br><br>I'll start deliberately minimal: <strong>client → job API → job store → worker pool</strong>. The job store is the durable source of truth for every job's definition and state, and that skeleton already guarantees we don't lose a job. Under pressure I'll grow it — a scheduler that efficiently finds due jobs, a task queue to decouple dispatch from execution, a coordinator for leader election and locks, and a dead-letter path for exhausted retries. Pick a box and let's push.",
  nodes:[
    {id:"client",name:"Client",sub:"submit / query",x:40,y:150},
    {id:"api",name:"Job API",sub:"CRUD + schedule",x:210,y:150},
    {id:"jobdb",name:"Job store",sub:"defs + state",x:380,y:150},
    {id:"worker",name:"Worker pool",sub:"execute",x:550,y:150},
    {id:"scheduler",name:"Scheduler",sub:"finds due jobs",x:380,y:40},
    {id:"queue",name:"Task queue",sub:"due jobs",x:550,y:40},
    {id:"coordinator",name:"Coordinator",sub:"leader / locks",x:210,y:40},
    {id:"deadletter",name:"Dead-letter",sub:"failed / retries",x:550,y:260},
  ],
  edges:[["client","api"],["api","jobdb"],["jobdb","worker"],["scheduler","jobdb"],["scheduler","queue"],["queue","worker"],["coordinator","scheduler"],["worker","deadletter"]],
  core:["client","api","jobdb","worker"],
  basic:["client","api","jobdb","worker"],
  requirements:{
    functional:[
      "Submit a one-time job to run at a specific time T, and submit recurring cron jobs (e.g. every 5 min, daily at midnight)",
      "Execute jobs reliably at their scheduled time, with automatic retries on failure",
      "Monitor a job: current status, next run time, and execution history",
    ],
    nonFunctional:[
      "Durability — a submitted job is never lost, even if a node dies immediately after acknowledging it",
      "At-least-once execution plus idempotency — every due job runs even across failures, and a duplicate run is harmless",
      "Timely execution at scale — fire within ~1-2s of due time at 10K+ executions/s, with 100M jobs registered and up to 1M due in the same second",
      "Fault tolerance — a scheduler or worker crash must not stall execution or double-fire jobs",
    ],
  },
  reqBuild:[
    {req:"Submit and store a one-time job, query its status",turns:[
      {who:"intv",text:"Start with the simplest thing that satisfies requirement one for a one-time job: a user submits run this at 14:00, and later asks what happened. What's the minimal path?"},
      {who:"cand",text:"The <strong>client</strong> calls the <strong>job API</strong> with a job definition — what to run (a handler id or a target endpoint), a payload, and a run-at time. The API validates it and writes a row to the <strong>job store</strong>, then acknowledges. Status queries are just a read of that same row. My four core boxes cover it. The key decision here is that the job store is the durable record: the moment the API returns success, the job survives crashes, because it's committed to durable storage before I ack — that's the durability requirement in its simplest form."},
      {who:"intv",text:"What does that job row actually look like, and how do you represent where the job is in its life?"},
      {who:"cand",text:"A row keyed by job id with the definition (handler, payload, run-at) plus a <strong>state machine</strong> field.<span class='eg'>status moves pending &rarr; queued &rarr; running &rarr; success, or &rarr; failed; plus next_run_at, attempt count, and last-updated timestamps.</span>A one-time job starts <code>pending</code> with <code>next_run_at = T</code>. Execution hasn't entered the picture yet — right now the worker could even poll the store directly for due rows. I'm keeping it dumb on purpose; efficient due-job discovery and decoupled dispatch are the next requirement, and I don't want to guess at that machinery before I need it."},
    ],resources:[
      {title:"Hello Interview — Job Scheduler breakdown",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
    ]},
    {req:"Execute jobs at their scheduled time (adds scheduler + queue)",reveal:["scheduler","queue"],turns:[
      {who:"intv",text:"Now make jobs actually fire at their time. In the minimal design, how does anything know a job is due, and why isn't that good enough?"},
      {who:"cand",text:"Right now the only option is workers polling the job store for rows where <code>next_run_at &le; now</code>. That works but it couples discovery to execution and hammers the store. Let me split responsibilities: add a <strong>scheduler</strong> whose only job is to scan for due jobs and hand them off, and a <strong>task queue</strong> that holds due jobs so dispatch is decoupled from execution. The scheduler finds due work and enqueues it; <strong>workers</strong> consume from the queue instead of polling the DB. That separation lets me scale finding-work and doing-work independently."},
      {who:"intv",text:"Walk me through the flow once a job comes due, and how the scheduler finds due jobs without a full table scan."},
      {who:"cand",text:"The scheduler queries an <strong>index on <code>next_run_at</code></strong> for a small window — jobs due in the next, say, few seconds — flips each from <code>pending</code> to <code>queued</code>, and pushes a task message onto the queue. A worker pulls the task, transitions it to <code>running</code>, executes the handler, and writes back <code>success</code> or <code>failed</code>.<span class='eg'>the due-scan is a range read like WHERE next_run_at &le; now+5s AND status='pending', ordered by next_run_at — bounded work per tick, not a scan of 100M rows.</span>The queue also absorbs bursts: if a thousand jobs come due at once, they buffer in the queue and workers drain them at their own pace rather than the scheduler blocking."},
      {who:"intv",text:"Why put a queue in the middle at all — why not have the scheduler call workers directly?"},
      {who:"cand",text:"Two reasons: <strong>backpressure</strong> and <strong>decoupling failure domains</strong>. If the scheduler called workers synchronously, a slow or saturated worker pool would back up the scanner and it would start missing due times. With a queue in between, the scheduler just enqueues and moves on; workers consume at whatever rate they can sustain, and a burst simply grows queue depth rather than dropping work. The queue also gives me a natural place to get <strong>at-least-once</strong> delivery later — a message stays until a worker acks it. So the scheduler's tick stays cheap and bounded no matter how the workers are doing."},
    ],resources:[
      {title:"Hello Interview — Job Scheduler breakdown",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
      {title:"System Design Primer — asynchronism",url:"https://github.com/donnemartin/system-design-primer"},
    ]},
    {req:"Recurring cron jobs and retries (adds dead-letter)",reveal:["deadletter"],turns:[
      {who:"intv",text:"Requirement extends two ways: cron jobs that recur, and jobs that fail and must be retried. Handle recurrence first — how does a daily job keep firing?"},
      {who:"cand",text:"A recurring job stores a <strong>cron expression</strong> instead of a single run-at. After each execution completes, I <strong>compute the next fire time</strong> from the cron spec and write it back to <code>next_run_at</code>, returning the job to <code>pending</code>. So a cron job is just a one-time job that reschedules itself.<span class='eg'>a job with cron 0 0 * * * runs, then next_run_at is set to tomorrow 00:00; the same due-scan on next_run_at picks it up again.</span>The scheduler doesn't care whether a job is one-time or recurring — it only looks at <code>next_run_at</code>. That keeps the scan path uniform."},
      {who:"intv",text:"Now retries. A job fails — how do you retry, and where does a job that keeps failing end up?"},
      {who:"cand",text:"On failure the worker increments the attempt count and reschedules the job with <strong>exponential backoff plus jitter</strong> — retry in 1s, then 2s, 4s, and so on, rather than immediately hammering a broken dependency.<span class='eg'>next_run_at = now + min(base * 2^attempt, cap) + random_jitter; attempt capped at, say, 5.</span>When retries are exhausted, I don't loop forever — the job goes to a <strong>dead-letter</strong> store for failed jobs. Let me add that box. It captures the job, its payload, and the last error so an operator can inspect a poison job and replay it after fixing the cause, instead of it silently vanishing or spinning retries forever."},
      {who:"intv",text:"Why route exhausted jobs to a separate dead-letter store rather than just marking them failed in the job store?"},
      {who:"cand",text:"Marking them <code>failed</code> in place is fine for state, but the dead-letter store gives me an explicit, monitorable <strong>queue of things needing human attention</strong> — I can alert on its depth, triage poison jobs, and <strong>replay</strong> them as a batch once the underlying bug or dependency is fixed. It also keeps failed work from cluttering the hot due-scan path. So the dead-letter is both a safety net (nothing is lost) and an operational surface (someone can see and act on failures). That satisfies recurrence and retries end to end — now I'd start hardening the distributed failure cases."},
    ],resources:[
      {title:"Cron",url:"https://en.wikipedia.org/wiki/Cron"},
      {title:"Hello Interview — Job Scheduler breakdown",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
    ]},
  ],
  systemDives:[
    {title:"Two schedulers double-fire the same job — and the SPOF",tag:"failover",reveal:["coordinator"],turns:[
      {who:"intv",text:"<span class='scenario'><b>Scenario:</b> you run <b>one</b> scheduler for availability reasons you now regret — when it crashes, nothing fires until it restarts, so it's a SPOF. You add a <b>second</b> scheduler. Now both scan the same due window and both enqueue job 42, which runs <b>twice</b>. You have a SPOF if you run one and double-fires if you run two. Resolve it.</span>"},
      {who:"cand",text:"I need multiple schedulers for availability but exactly-one <em>owner</em> per job at scan time. The clean answer is a <strong>coordinator</strong> for leader election and partition assignment — let me add it. The simplest form: elect a single active leader via <strong>ZooKeeper or etcd</strong>; the leader does the scanning, standbys wait. If the leader dies, the coordinator's lease expires and a standby is elected within seconds — no SPOF, and only one scanner runs so no double-enqueue. The coordinator is the arbiter of who is allowed to act."},
      {who:"intv",text:"A single leader scanning 100M jobs is a scaling ceiling. Can you use all the schedulers without reintroducing double-fires?"},
      {who:"cand",text:"Yes — move from one leader to <strong>partitioned ownership</strong>. The coordinator assigns each scheduler a disjoint slice of the job space — by hash of job id or by shard — so every job has exactly one owner scanning it, and all schedulers work in parallel. Double-fires are impossible because two schedulers never own the same job. When a scheduler dies, the coordinator <strong>reassigns its partitions</strong> to survivors, so it's both horizontally scalable and fault tolerant. The invariant the coordinator enforces is: one owner per partition at any instant."},
      {who:"intv",text:"During a reassignment the old owner might still think it owns a partition while the new owner starts. Now both scan it briefly. How do you stop that split-brain double-fire?"},
      {who:"cand",text:"<strong>Fencing tokens</strong>. Each partition assignment carries a monotonically increasing token; when the scheduler enqueues or claims a job it presents its token, and the job store (or queue) rejects any action from a stale token. So even if a slow old owner wakes up believing it still holds the partition, its writes are fenced off because a higher token has been issued. Combined with a per-job atomic claim — flip <code>pending &rarr; queued</code> conditionally, only if still <code>pending</code> — even an overlap window can't enqueue the same job twice. Leader election gives liveness; fencing plus the conditional claim gives safety."},
    ],resources:[
      {title:"Leader election",url:"https://en.wikipedia.org/wiki/Leader_election"},
      {title:"ZooKeeper overview",url:"https://zookeeper.apache.org/doc/current/zookeeperOver.html"},
      {title:"Hello Interview — Job Scheduler (coordination)",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
    ]},
    {title:"At-least-once vs exactly-once execution",tag:"durability",turns:[
      {who:"intv",text:"<span class='scenario'><b>Scenario:</b> a job charges a customer $50. It's enqueued, a worker picks it up, runs the charge, but crashes before acking the queue. The message reappears and another worker runs it — the customer is charged <b>twice</b>. You promised at-least-once. How do you keep the guarantee useful?</span>"},
      {who:"cand",text:"I'll be blunt about the theory first: true <strong>exactly-once execution</strong> across independent failure domains is impossible — you cannot atomically both run a side effect and record that you ran it. So I commit to <strong>at-least-once delivery plus idempotent execution</strong>, which gives exactly-once <em>effects</em>, which is what the customer actually cares about. The redelivery you described is correct behavior; the fix is making the second run a no-op."},
      {who:"intv",text:"Concretely, how does the second run of that charge become a no-op?"},
      {who:"cand",text:"Every execution carries a stable <strong>idempotency key</strong> — the job id plus the run's scheduled time (so run N and run N+1 of a cron job differ).<span class='eg'>execution_id = jobId + ':' + scheduledFireTime; the charge service records that id and refuses a second charge for the same id.</span>The effect is deduplicated at the <strong>side-effecting boundary</strong>: the worker passes the key to the downstream (payment API, DB write) which does an insert-if-absent on that key. So even if the job runs three times, the money moves once. I push idempotency to where the effect lands because that's the only place it can be truly enforced."},
      {who:"intv",text:"Not every downstream supports idempotency keys. What's your fallback, and what do you tell users?"},
      {who:"cand",text:"Where I control the downstream, I use the key. Where I don't, I offer a best-effort dedup layer — a <strong>processed-executions table</strong> the worker checks-and-sets before running: if the execution id is already marked done, skip. It shrinks the double-run window to the gap between doing the effect and recording it, but can't eliminate it for a non-idempotent external call. So the contract I document is explicit: the platform guarantees at-least-once, and job authors <strong>must make handlers idempotent</strong> — the same execution id may be delivered more than once. That honesty is better than pretending exactly-once and quietly double-charging someone."},
    ],resources:[
      {title:"Idempotence",url:"https://en.wikipedia.org/wiki/Idempotence"},
      {title:"Hello Interview — Job Scheduler (execution semantics)",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
    ]},
    {title:"A million jobs due at midnight — hot polling and thundering herd",tag:"scaling",turns:[
      {who:"intv",text:"<span class='scenario'><b>Scenario:</b> of your <b>100M</b> jobs, humans love round numbers, so <b>1M</b> are cron jobs due at exactly 00:00:00. At midnight the due-scan returns a million rows in one tick, the job store gets hammered by polling, and a wall of tasks hits your workers at once. Everything spikes. Fix the herd.</span>"},
      {who:"cand",text:"Two distinct problems: the <strong>hot due-scan</strong> on the store and the <strong>execution thundering herd</strong>. For the scan, I never do a naive full-table poll — I keep a tight <strong>index on <code>next_run_at</code></strong> and read a bounded window, and I move the hottest tier into a <strong>time-bucketed delay structure</strong>: a <strong>Redis sorted set</strong> scored by fire time, so finding due jobs is an O(log n) range pop rather than a DB scan.<span class='eg'>ZRANGEBYSCORE due 0 now — pop just what's due, no scanning of the other 99M.</span>The scheduler polls that small structure frequently and only touches the durable store for state transitions."},
      {who:"intv",text:"Even if you find the million jobs efficiently, they're all due at the same instant. Do a million things really have to fire in second zero?"},
      {who:"cand",text:"Almost never — and this is the key insight. A job scheduled for midnight rarely needs millisecond precision; it needs to run <em>around</em> midnight. So I <strong>spread the herd with jitter</strong>: when computing next_run_at for popular cron times, I add a small random offset within a tolerance window — a few seconds to a couple of minutes depending on the job's SLA — so a million midnight jobs smear across a window instead of stacking on one tick.<span class='eg'>next_run_at = 00:00:00 + rand(0, 120s), so ~8K/s over two minutes instead of 1M in one second.</span>That alone converts a spike into a manageable stream. For jobs that genuinely need exact timing, I don't jitter, but those are rare."},
      {who:"intv",text:"Suppose after jitter you still have a sustained burst bigger than the workers can drain. What keeps the system stable rather than collapsing?"},
      {who:"cand",text:"The <strong>task queue is the shock absorber</strong>. The scheduler enqueues at whatever rate work comes due; workers consume at their sustainable rate; the difference just becomes queue depth, which is fine and self-draining. I <strong>autoscale the worker pool</strong> on queue depth so capacity follows load, and I partition the scheduler so the scan itself scales horizontally. If depth grows unboundedly I apply <strong>backpressure</strong> — throttle lower-priority jobs and let the queue buffer — rather than dropping work. So the herd is handled by three compounding moves: cheap due-discovery (sorted set), spreading the arrival (jitter), and absorbing the remainder (queue + autoscaling). Peak store and worker load become quantities I set, not functions of how many jobs picked midnight."},
    ],resources:[
      {title:"Redis sorted sets",url:"https://redis.io/docs/latest/develop/data-types/sorted-sets/"},
      {title:"Hello Interview — Job Scheduler (scaling)",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
      {title:"System Design Primer — asynchronism",url:"https://github.com/donnemartin/system-design-primer"},
    ]},
    {title:"A worker dies mid-execution — lost or run twice?",tag:"failover",turns:[
      {who:"intv",text:"<span class='scenario'><b>Scenario:</b> a worker dequeues job 42, transitions it to <code>running</code>, starts a 3-minute data export, and at minute two the pod is SIGKILLed. The job never finished and never acked. Is job 42 lost forever, or does it silently run twice? Walk me through what happens.</span>"},
      {who:"cand",text:"Neither, if the queue uses a <strong>visibility timeout</strong> instead of deleting on dequeue. When the worker pulled job 42, the message wasn't removed — it was made <em>invisible</em> for a lease period. The worker must <strong>ack</strong> to delete it on success. Because the worker died without acking, the visibility timeout expires and the queue <strong>re-delivers</strong> job 42 to another worker. So the job is not lost — that's the at-least-once guarantee doing its job. It may run partially twice, which is exactly why handlers must be idempotent with the execution id."},
      {who:"intv",text:"Your export takes 3 minutes but the visibility timeout is 30 seconds. It re-delivers while the first worker is still alive and working. Now two workers run it concurrently. Fix that without just cranking the timeout to hours."},
      {who:"cand",text:"A fixed long timeout is bad — a genuine crash then leaves the job stuck for hours. Instead the worker <strong>heartbeats to extend its lease</strong> while it works: every few seconds it renews the visibility timeout, proving it's alive.<span class='eg'>lease starts at 30s; worker calls extend-lease every 10s; if the worker dies, no more extensions, lease lapses in ~30s and the job re-delivers.</span>So a long-running job holds its lease as long as it's healthy, and a dead worker releases it promptly. I also set a hard <strong>execution timeout</strong> — if a job blows past a max runtime it's killed and treated as failed for retry, so a wedged handler can't hold a lease forever."},
      {who:"intv",text:"On restart, the crashed worker's job re-runs — but what about jobs that were due <em>during</em> a broader outage, say the whole scheduler was down for 10 minutes? Are those just missed?"},
      {who:"cand",text:"No — this is why the durable store, not the queue, is the source of truth for what's due. On recovery the scheduler <strong>scans for overdue jobs</strong>: any row with <code>next_run_at &lt; now</code> still in <code>pending</code> is due and simply gets enqueued now, a little late but not lost. Missing a fire time degrades timeliness, not durability. For each such job I decide by policy whether to <strong>run every missed occurrence or just the latest</strong> — for a report you might skip catch-up and run once; for billing you run each. Because next_run_at lives in the durable store and the scan is idempotent, a scheduler outage becomes a bounded lateness on restart, never a silently dropped execution."},
    ],resources:[
      {title:"Kafka documentation — delivery semantics",url:"https://kafka.apache.org/documentation/"},
      {title:"Hello Interview — Job Scheduler (worker failure)",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
      {title:"Idempotence",url:"https://en.wikipedia.org/wiki/Idempotence"},
    ]},
  ],
  q:{
    client:[
      {l:"easy",tag:"concept",q:"What does the client send on submit, and how does it query status?",turns:[
        {who:"intv",text:"A user submits run this export at 14:00 and later checks on it. What does the client actually send, and how does it track the job afterward?"},
        {who:"cand",text:"On submit the client sends a job definition — a handler id or target, a payload, and a schedule (a run-at time or a cron expression) — and gets back a <strong>job id</strong>. It stores that id and uses it for everything after: <span class='eg'>GET /jobs/{id} returns status (pending / queued / running / success / failed), next_run_at, and recent run history.</span>The client is a <strong>view</strong> of server truth — it never assumes a job ran; it reads the authoritative state from the job store via the API. For recurring jobs it shows the last few executions and the next scheduled fire time."},
        {who:"intv",text:"How does the user know an execution actually happened without polling constantly?"},
        {who:"cand",text:"Two options depending on the use case. For dashboards, the client polls the status endpoint at a relaxed interval — status changes are not urgent to display. For programmatic consumers I prefer <strong>completion callbacks / webhooks</strong>: when a job reaches a terminal state the system posts to a user-supplied URL, so they learn of success or failure without polling at all. Either way the truth is the job store's execution history; the client just surfaces it. Polling is a convenience, not a correctness mechanism."},
      ],resources:[
        {title:"Hello Interview — Job Scheduler",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
      ]},
      {l:"medium",tag:"scaling",q:"A batch client submits a flood of jobs — protect the API.",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> an automated client submits <b>50K</b> jobs in a burst (someone backfilling a year of scheduled reports), each a separate POST. That's a spike far above steady-state submit rate. How does the client side avoid melting your API?</span>"},
        {who:"cand",text:"Two levers. First, offer a <strong>batch submit</strong> endpoint so 50K jobs arrive as a handful of bulk requests instead of 50K round trips — one durable write of many rows, far less per-request overhead. Second, the client should respect <strong>rate-limit responses</strong>: when the API returns <code>429</code>, back off with jitter and retry rather than hammering. A well-behaved client submits at a sustainable rate; a misbehaving one gets throttled at the edge. The submit path is a write to the durable store, so I want it bounded and batched, not a firehose of tiny writes."},
        {who:"intv",text:"If the batch is huge, does the client wait for all 50K to be durably stored before it gets an ack?"},
        {who:"cand",text:"For very large batches I make submit <strong>asynchronous</strong>: the API accepts the batch, writes it to a durable intake, and returns a <strong>batch id</strong> immediately with status <code>accepted</code>. The client then polls the batch id to see how many were validated and scheduled. This keeps the request fast and bounded regardless of batch size, and the durability guarantee is preserved because the intake write is durable before the ack. The client treats the batch id like a receipt — the work is safely captured even before every individual job is fully materialized."},
      ],resources:[
        {title:"System Design Primer — rate limiting",url:"https://github.com/donnemartin/system-design-primer"},
        {title:"ByteByteGo",url:"https://bytebytego.com/"},
      ]},
      {l:"medium",tag:"failover",q:"Submit request times out — was the job created?",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> the client POSTs a job, the network stalls, and after 10s the client times out with no response. The user has no idea whether the job was created. They hit submit again. How do you avoid creating the same job twice?</span>"},
        {who:"cand",text:"The client attaches a <strong>client-generated idempotency key</strong> to the submit and reuses the <em>same</em> key on retry. So the retry is safe: if the first request actually reached the API and created the job, the server recognizes the key and returns the <em>same</em> job id rather than creating a duplicate. The user ends up with exactly one scheduled job no matter how many times the flaky network makes them retry. Without this, timeouts on a write path silently create duplicate jobs — which for a payment cron would mean double-charging."},
        {who:"intv",text:"How long does the server remember that idempotency key, and what if the retry comes much later?"},
        {who:"cand",text:"The server persists the key alongside the created job with a retention window — say 24 hours — long enough to cover any realistic retry. Within that window a repeat key returns the original job id; after it, the key is forgotten and a repeat would create a new job, which is acceptable because a retry days later is really a new intent. For safety I make the dedup a <strong>unique constraint on the idempotency key</strong> in the store, so even two concurrent retries racing can't both insert — one wins, the other reads back the existing job. Correctness doesn't depend on timing luck."},
      ],resources:[
        {title:"Idempotence",url:"https://en.wikipedia.org/wiki/Idempotence"},
        {title:"Hello Interview — Job Scheduler",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
      ]},
    ],
    api:[
      {l:"medium",tag:"concept",q:"What does the Job API own beyond a thin CRUD layer?",turns:[
        {who:"intv",text:"You drew a Job API box. Beyond writing rows, what does it actually own — especially for a cron submission?"},
        {who:"cand",text:"It owns the edge concerns and the correctness of what enters the store: authentication, <strong>validation</strong>, idempotency, and rate limiting. For a cron job the critical piece is <strong>validating the cron expression</strong> and computing the first <code>next_run_at</code> before persisting — a malformed spec should be rejected at submit, not discovered by the scheduler at 3am.<span class='eg'>parse 0 0 * * *, confirm it's valid, compute the next fire time, reject garbage like 99 * * * * with a 400.</span>It also enforces limits — max frequency, payload size — so no single job can, say, ask to run every millisecond."},
        {who:"intv",text:"Where does the API stop and the scheduler begin? Why not let the API also trigger execution?"},
        {who:"cand",text:"Clean separation of concerns. The API is the <strong>synchronous, user-facing write path</strong> — it validates and durably records intent, then returns. The <strong>scheduler</strong> is the asynchronous engine that later acts on that recorded intent by finding due jobs. Keeping them apart means submit latency is independent of execution load: a midnight execution storm never slows down a user submitting a new job, and vice versa. The API's contract is simply if I acked, your job is durably scheduled — everything about <em>when and how</em> it runs is downstream."},
      ],resources:[
        {title:"Cron",url:"https://en.wikipedia.org/wiki/Cron"},
        {title:"Hello Interview — Job Scheduler",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
      ]},
      {l:"medium",tag:"scaling",q:"Submit and status traffic spikes — scale the API tier.",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> status-query traffic is <b>100x</b> your submit traffic — dashboards and webhooks-checkers polling job state constantly, tens of thousands of reads/s, while submits are a trickle. How do you scale the API so reads don't starve writes?</span>"},
        {who:"cand",text:"Split the read and write paths so they scale independently. The API tier is <strong>stateless</strong>, so I scale it horizontally behind a load balancer freely. Status reads are the bulk and are cache-friendly — a job's status changes at most a few times in its life — so I serve them from <strong>read replicas</strong> of the job store and a short-TTL cache, keeping the write-primary reserved for submits and the scheduler's state transitions. Reads being slightly stale (a status a second behind) is harmless for a dashboard. So the 100x read load lands on replicas and cache, never contending with the durable write path."},
        {who:"intv",text:"Status reads and the scheduler's due-scan both hit the job store. Do they compete?"},
        {who:"cand",text:"They shouldn't, and I keep them apart deliberately. Status reads go to <strong>read replicas</strong>; the scheduler's due-scan and state writes go to the <strong>primary</strong> (or to the dedicated sorted-set index for the hot tier). Because status reads tolerate staleness they're a perfect replica workload, while the scheduler needs current state to claim jobs, so it reads authoritative. Routing them to different nodes means a dashboard-refresh storm can't slow down finding-and-firing due jobs — the timely-execution requirement is protected from read load."},
      ],resources:[
        {title:"System Design Primer — scaling reads & replicas",url:"https://github.com/donnemartin/system-design-primer"},
        {title:"ByteByteGo",url:"https://bytebytego.com/"},
      ]},
      {l:"medium",tag:"failover",q:"The API acks a submit but the store write didn't commit — durability hole?",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> under load your API returns <code>201 Created</code> to <b>5K</b> submitting clients, but a subset of those writes were only in a buffer and the store node crashed before flushing them. Those jobs are gone but users think they're scheduled. That violates durability. Close the hole.</span>"},
        {who:"cand",text:"The bug is acking before the write is durable. The rule is <strong>never return success until the job is committed to durable, replicated storage</strong>. Concretely the API waits for the store to confirm a <strong>quorum-acknowledged write</strong> — a majority of replicas have it on durable media — before sending <code>201</code>. Yes, that adds a few milliseconds to submit, but durability is the whole promise of this system; a job I acked must survive a node loss. I'd rather a slightly slower submit than a job that silently evaporates."},
        {who:"intv",text:"If the store is briefly unavailable and can't confirm the durable write, what does the API return?"},
        {who:"cand",text:"I <strong>fail closed</strong> on submit — return a <code>503</code> and do <em>not</em> ack, so the client retries (safely, using its idempotency key) rather than believing a job exists that doesn't. This is the opposite of a status read, where I'd happily serve slightly stale data; on the write path I never trade durability for availability. Optionally I front submits with a durable, replicated intake log so I can accept the write even if the main store is momentarily slow — but I still only ack once <em>something</em> durable holds the job. The invariant is simple: an ack is a durability guarantee, never a hope."},
      ],resources:[
        {title:"System Design Primer — availability & consistency",url:"https://github.com/donnemartin/system-design-primer"},
        {title:"Hello Interview — Job Scheduler",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
      ]},
    ],
    jobdb:[
      {l:"medium",tag:"concept",q:"Model the job store schema and the state machine.",turns:[
        {who:"intv",text:"Pick your datastore for jobs and defend the schema. Give me the row model and how a job moves through its life."},
        {who:"cand",text:"I want a <strong>durable, strongly-consistent</strong> store for the source of truth — a relational DB or a store with conditional writes — because state transitions must be atomic to prevent double-claims. The core table is keyed by job id: definition (handler, payload), schedule (a run-at or cron expression), <code>status</code>, <code>next_run_at</code>, <code>attempt</code>, an <strong>owner/lease</strong> field, and timestamps. Execution history lives in a separate <code>runs</code> table (one row per attempt) so I keep an audit trail.<span class='eg'>status transitions: pending &rarr; queued &rarr; running &rarr; success | failed; failed with attempts left &rarr; pending; failed exhausted &rarr; dead-letter.</span>"},
        {who:"intv",text:"Why keep run history in a separate table rather than just updating the job row?"},
        {who:"cand",text:"Because a recurring job runs thousands of times and users need to see <em>each</em> execution — when it ran, how long, success or failure, the error. If I overwrote the job row I'd lose history. So the job row holds <strong>current state and next fire time</strong> (the hot, mutable part the scheduler scans), and an append-only <strong>runs table</strong> holds the immutable log of every attempt (the cold, queryable part for monitoring). This split also keeps the hot due-scan index small — it only indexes live jobs by next_run_at, not the millions of historical runs. Hot state and cold history have different access patterns, so I store them separately."},
      ],resources:[
        {title:"Hello Interview — Job Scheduler (data model)",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
        {title:"System Design Primer — data model",url:"https://github.com/donnemartin/system-design-primer"},
      ]},
      {l:"hard",tag:"scaling",q:"100M jobs and a hot due-scan — index and shard the store.",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> <b>100M</b> registered jobs, and the scheduler must find the ones due each second. A naive <code>SELECT WHERE next_run_at &le; now</code> scans the whole table every tick and pins the DB. Meanwhile writes for state transitions pile up. Make finding due jobs cheap at this scale.</span>"},
        {who:"cand",text:"First, an <strong>index on <code>next_run_at</code></strong> (with status), so the due-scan is a bounded range read — pull only jobs due in the next few seconds, ordered, not a scan of 100M rows. Second, for the hot near-term tier I front the store with a <strong>Redis sorted set scored by fire time</strong>: the scheduler pops due jobs in O(log n) and only writes state transitions back to the durable store.<span class='eg'>ZRANGEBYSCORE due -inf now to pop, then persist the queued transition — the durable store isn't in the tight polling loop.</span>Jobs far in the future don't sit in the hot structure at all — they're loaded in as their fire time approaches."},
        {who:"intv",text:"One store node can't hold 100M jobs and take all the transition writes. How do you shard, and how does that interact with the scheduler?"},
        {who:"cand",text:"I <strong>shard by job id</strong> (hash) so the 100M jobs and their writes spread across many nodes, and I align that with the <strong>scheduler's partitioning</strong>: each scheduler owns a set of shards and scans only those. That makes finding-due-work embarrassingly parallel — no single scanner and no single hot shard. A single-row conditional claim stays cheap per shard. The one thing sharding-by-id doesn't help is a temporal hotspot (everything due at midnight), but that's solved separately by jitter spreading fire times. So id-sharding scales capacity and throughput, and jitter flattens the time axis — the two are orthogonal and both needed."},
      ],resources:[
        {title:"System Design Primer — sharding",url:"https://github.com/donnemartin/system-design-primer"},
        {title:"Redis sorted sets",url:"https://redis.io/docs/latest/develop/data-types/sorted-sets/"},
      ]},
      {l:"hard",tag:"durability",q:"A store node dies — are scheduled jobs lost?",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> the node holding a shard has a disk failure and won't come back. That shard held the definitions and next-run times for millions of jobs — including a customer's daily billing run. Are those jobs gone? Give me your durability story.</span>"},
        {who:"cand",text:"If a shard were a single node, losing it would silently stop millions of jobs from ever firing again — a catastrophic, invisible failure. So every shard is a <strong>replica group</strong> (e.g. 3 replicas across AZs) with <strong>synchronous quorum-acknowledged writes</strong>: a submit or a state transition isn't acked until a majority of replicas hold it durably. A single disk failure loses nothing — surviving replicas have every job, and a fresh replica rebuilds from them. This is why the API waits for the durable quorum ack before telling the user their job is scheduled: the durability promise is enforced at the store's write path."},
        {who:"intv",text:"Quorum writes add latency to every state transition, and the scheduler does a lot of them. Justify the cost."},
        {who:"cand",text:"I'll pay it because losing a job is worse than a slightly slower transition, and a quorum write is only a few milliseconds — negligible against a job's schedule granularity of seconds. Where I optimize is by <strong>keeping the durable writes coarse</strong>: the hot polling loop runs against the in-memory sorted set, and I persist transitions in batches where safe, so I'm not doing a quorum round-trip on every tick for every job. The definition and terminal states go through durable quorum; the ephemeral in-flight bookkeeping can be cheaper. So durability is scoped tightly to what must survive — the job's existence and its committed outcomes."},
      ],resources:[
        {title:"System Design Primer — replication",url:"https://github.com/donnemartin/system-design-primer"},
        {title:"Hello Interview — Job Scheduler (durability)",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
      ]},
      {l:"hard",tag:"failover",q:"The store primary fails mid-scan — promote without losing claims.",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> the write-primary for a shard crashes while the scheduler is actively claiming due jobs. You promote a replica. Two minutes later the old primary rejoins, still thinking it's primary. Now two nodes could accept job-state writes. What breaks and how do you prevent it?</span>"},
        {who:"cand",text:"This is <strong>split-brain</strong>, and here it means two primaries could each claim job 42 to a different scheduler — a double-fire that survives as two executions. Prevention is <strong>consensus-based promotion</strong>: leader election (Raft/Paxos or the coordinator) grants a monotonically increasing <strong>epoch</strong>. The promoted primary writes under a higher epoch; when the stale old primary rejoins, replicas <strong>reject its writes via the fencing token</strong> and it demotes and re-syncs. There's never a window where two nodes hold the current epoch, so a job is never claimed by two authorities."},
        {who:"intv",text:"During the election window, transitions on that shard pause. Jobs due right then are late. Acceptable?"},
        {who:"cand",text:"Yes — it's the CAP call, and I choose <strong>consistency over availability for writes</strong> during the partition. A few seconds of paused claiming on that shard means those jobs fire a few seconds late, which is a timeliness blip, not a correctness failure — and the durable <code>next_run_at</code> means they'll all still fire on recovery via the overdue scan. Double-firing a billing job, by contrast, is unacceptable. So I pause, elect, fence, resume. Reads (status queries) stay up from replicas throughout. Late-but-correct beats fast-but-double-fired, and using a managed store that does this fencing internally is a strong reason not to hand-roll failover."},
      ],resources:[
        {title:"Leader election",url:"https://en.wikipedia.org/wiki/Leader_election"},
        {title:"System Design Primer — consistency & availability",url:"https://github.com/donnemartin/system-design-primer"},
      ]},
    ],
    worker:[
      {l:"medium",tag:"concept",q:"How does a worker execute a task safely — lease, run, ack?",turns:[
        {who:"intv",text:"A worker pulls a task off the queue. Walk me through exactly how it runs the job and reports back, and where idempotency comes in."},
        {who:"cand",text:"The worker dequeues a task with a <strong>visibility-timeout lease</strong>, transitions the job to <code>running</code>, and executes the handler with the job's payload and its <strong>execution id</strong> (job id + scheduled fire time). On success it writes <code>success</code>, appends a run record, and <strong>acks</strong> the queue to delete the message. On failure it records the error and schedules a retry. The execution id is the key to idempotency: the worker passes it to any side-effecting downstream so a re-delivered task produces the same effect once.<span class='eg'>charge(executionId, amount) — the payment service dedups on executionId, so a retry is a no-op.</span>"},
        {who:"intv",text:"Why lease-then-ack rather than just deleting the task when you dequeue it?"},
        {who:"cand",text:"Because delete-on-dequeue is <strong>at-most-once</strong> — if the worker crashes after dequeuing, the job is gone forever, violating durability. Lease-then-ack is <strong>at-least-once</strong>: the message stays (invisible) until the worker proves completion by acking, so a crash mid-run means the lease lapses and the job re-delivers to another worker. I deliberately choose the semantics where a failure causes a <em>re-run</em> (harmless with idempotency) over one where a failure causes a <em>lost execution</em> (unrecoverable). Losing a scheduled job is the one thing this system must never do."},
      ],resources:[
        {title:"Kafka documentation — consumer semantics",url:"https://kafka.apache.org/documentation/"},
        {title:"Idempotence",url:"https://en.wikipedia.org/wiki/Idempotence"},
      ]},
      {l:"medium",tag:"scaling",q:"10K executions/s with uneven job durations — size the pool.",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> steady-state is <b>10K</b> executions/s, but job runtimes vary wildly — some finish in 10ms, some run for minutes. A naive fixed worker pool either idles or falls behind. How do you scale execution?</span>"},
        {who:"cand",text:"Workers are <strong>stateless consumers</strong> of the queue, so I <strong>autoscale the pool on queue depth and consumer lag</strong> — when the backlog grows, add workers; when it drains, scale in. Because dispatch is decoupled through the queue, capacity can track load without touching the scheduler or store. For the runtime variance I <strong>separate pools by workload class</strong> — a fast lane for short jobs and a separate lane for long-running jobs — so a handful of multi-minute exports don't head-of-line-block thousands of 10ms tasks waiting behind them."},
        {who:"intv",text:"How do you keep one tenant's giant batch from starving everyone else's jobs?"},
        {who:"cand",text:"Fairness and isolation. I <strong>partition queues by priority and/or tenant</strong> and give workers weighted attention, so one tenant flooding the system can't monopolize the whole pool — their tasks pile in their partition while others drain normally. I also enforce <strong>per-tenant concurrency limits</strong>. Combined with autoscaling, a big batch just means that tenant's lane runs at its cap and takes longer, rather than degrading the timeliness of every other job. The scarce resource is worker slots, so I schedule them fairly rather than first-come-first-served across tenants."},
      ],resources:[
        {title:"System Design Primer — asynchronism & queues",url:"https://github.com/donnemartin/system-design-primer"},
        {title:"ByteByteGo",url:"https://bytebytego.com/"},
      ]},
      {l:"hard",tag:"durability",q:"A worker crashes mid-execution — job lost or resumed?",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> a worker is 90 seconds into a job when its pod is OOM-killed. It never acked. Is that execution lost? And when it re-runs, how do you avoid the side effects from the first 90 seconds happening twice?</span>"},
        {who:"cand",text:"Not lost. The worker held the task under a <strong>visibility-timeout lease</strong> and never acked, so once the lease lapses the queue <strong>re-delivers</strong> the task to another worker — the at-least-once guarantee. The re-run risk is the first 90 seconds' side effects repeating. I handle that with <strong>idempotency keyed on the execution id</strong>: any effect the job produced carries that id, and the downstream dedups it, so replaying the whole job re-applies each effect at most once. For multi-step jobs I checkpoint completed steps keyed by execution id so a re-run <strong>skips already-done steps</strong> rather than redoing them."},
        {who:"intv",text:"What if the crash happened <em>after</em> the side effect but <em>before</em> writing success? The re-run redoes a non-idempotent action."},
        {who:"cand",text:"That's the fundamental gap — you can't atomically do an external effect and record it. My answer is to make the boundary idempotent wherever possible (execution id dedup at the downstream), and where the downstream truly can't dedup, to make the effect itself <strong>check-then-act on the execution id</strong>: record intent-to-do before the effect and confirmed-done after, so a re-run sees intent-without-confirmation and can query the downstream to learn the true outcome before re-doing. It shrinks but can't fully close the window for a non-idempotent external call — which is why the platform contract explicitly requires idempotent handlers. I don't pretend to give exactly-once where physics doesn't allow it."},
      ],resources:[
        {title:"Idempotence",url:"https://en.wikipedia.org/wiki/Idempotence"},
        {title:"Hello Interview — Job Scheduler (worker failure)",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
      ]},
      {l:"hard",tag:"failover",q:"A long job outlives its lease — premature re-delivery.",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> visibility timeout is 60s but a legitimate job takes 5 minutes. At 60s the queue re-delivers it to a second worker while the first is still running — now two workers execute the same job concurrently. How do you fix this without setting a giant timeout that leaves crashed jobs stuck for ages?</span>"},
        {who:"cand",text:"The worker <strong>heartbeats to extend its lease</strong> while healthy. It starts with a modest visibility timeout (60s) and, as long as it's making progress, calls extend-lease periodically to renew it.<span class='eg'>renew every 20s; a healthy 5-minute job keeps extending; a crashed worker stops renewing and the lease lapses in ~60s, triggering re-delivery.</span>So a long job holds its lease exactly as long as it's alive, and a dead worker releases promptly — I get both timely re-delivery on crash and no premature double-run on a slow-but-healthy job."},
        {who:"intv",text:"A worker hangs — alive enough to keep heartbeating but wedged and making no progress. It holds the lease forever. Now what?"},
        {who:"cand",text:"That's why I also enforce a hard <strong>execution timeout / max runtime</strong> independent of the lease: if a job exceeds its allowed wall-clock, the worker (or a supervisor) <strong>kills it</strong> and marks it failed for retry, regardless of heartbeats. Heartbeating proves the <em>process</em> is alive; the execution timeout bounds how long the <em>job</em> may run. A wedged handler thus can't hold a slot forever — it's terminated, the lease releases, and the job either retries or, after exhausting attempts, lands in the dead-letter store for a human to look at. Two independent limits: liveness (heartbeat) and progress (max runtime)."},
      ],resources:[
        {title:"Kafka documentation — session & heartbeat",url:"https://kafka.apache.org/documentation/"},
        {title:"Hello Interview — Job Scheduler (leases)",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
      ]},
    ],
    scheduler:[
      {l:"medium",tag:"concept",q:"How does the scheduler find due jobs efficiently?",turns:[
        {who:"intv",text:"The scheduler's core job is finding which jobs are due right now. With millions of jobs, how do you do that without scanning everything every tick?"},
        {who:"cand",text:"I keep jobs indexed by fire time and only ever look at the near edge. The durable store has an <strong>index on <code>next_run_at</code></strong> so a due-scan is a bounded range read — jobs due in the next few seconds — not a full scan. For the hot tier I use a <strong>time-bucketed delay structure</strong>, a <strong>Redis sorted set scored by fire time</strong>, so the scheduler pops due jobs in O(log n).<span class='eg'>poll every second: ZRANGEBYSCORE due 0 now, claim each, enqueue it, then set next_run_at ahead (cron) or mark terminal (one-time).</span>Future jobs aren't in the hot set at all — they're pulled in as their fire time nears. Work per tick is proportional to what's actually due, not to the catalog size."},
        {who:"intv",text:"How does the scheduler avoid claiming a job that another scheduler is also scanning?"},
        {who:"cand",text:"Each job is claimed with an <strong>atomic conditional transition</strong> — flip <code>pending &rarr; queued</code> only if it's still <code>pending</code> — so exactly one scheduler wins the claim and the others' updates affect zero rows. On top of that, the coordinator gives each scheduler a <strong>disjoint partition</strong> of jobs so ideally no two even look at the same job. The conditional claim is the safety backstop for the brief overlap during a partition reassignment. Between partitioning (avoid contention) and the atomic claim (make contention safe), a job is enqueued exactly once per fire time."},
      ],resources:[
        {title:"Redis sorted sets",url:"https://redis.io/docs/latest/develop/data-types/sorted-sets/"},
        {title:"Hello Interview — Job Scheduler (finding due jobs)",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
      ]},
      {l:"hard",tag:"scaling",q:"Scan cost grows with 100M jobs — scale the scheduler.",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> you grow to <b>100M</b> jobs and a single scheduler polling the due structure every second can't keep up — the tick takes longer than a second and jobs start firing late. Scale the scheduler out without double-firing.</span>"},
        {who:"cand",text:"Partition the work. The coordinator splits the job space into <strong>N partitions</strong> (by hash of job id or by shard) and assigns each to a scheduler instance, so each scans only its slice and they run fully in parallel. Add a scheduler, the coordinator rebalances partitions, throughput scales linearly. Because partitions are disjoint, two schedulers never scan the same job, so parallelism doesn't create double-fires. The per-partition hot structure (its own sorted set) keeps each scan bounded, and I size N so each tick comfortably finishes within its polling interval."},
        {who:"intv",text:"A temporal spike — a million jobs at midnight — lands unevenly. Does partitioning by id help there?"},
        {who:"cand",text:"Partitioning by id spreads jobs evenly by <em>identity</em> but not by <em>fire time</em>, so a midnight spike hits all partitions at once — it doesn't overload one partition, but it does mean every scheduler is busy simultaneously. Id-partitioning handles that fine because the load is spread across all of them. The remaining spike is flattened on the <em>time</em> axis by <strong>jitter</strong> — smearing popular cron times across a tolerance window — and absorbed by the <strong>queue</strong> downstream. So scheduler scaling (partition by id) and spike flattening (jitter + queue) are separate, complementary levers; I need both to hit timely execution at 100M jobs with a midnight herd."},
      ],resources:[
        {title:"System Design Primer — sharding & scaling",url:"https://github.com/donnemartin/system-design-primer"},
        {title:"Hello Interview — Job Scheduler (scaling)",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
      ]},
      {l:"hard",tag:"durability",q:"The scheduler crashes for 10 minutes — are due jobs missed?",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> a scheduler (owning some partitions) crashes and its standby takes ~10 minutes to fully take over. During that window, thousands of jobs became due. Are those executions lost, and how does the system recover them?</span>"},
        {who:"cand",text:"Not lost, because due-ness lives in the <strong>durable store</strong> (<code>next_run_at</code>), not in the scheduler's memory. On takeover the new owner does an <strong>overdue scan</strong>: any job with <code>next_run_at &lt; now</code> still in <code>pending</code> is due and simply enqueued now — a bit late but present. A scheduler outage degrades <strong>timeliness, not durability</strong>: jobs fire late by roughly the outage duration, then the backlog drains. The recovery path is identical to normal scanning; there's no special catch-up code, because the scan is naturally idempotent over the durable next_run_at."},
        {who:"intv",text:"For a cron job that should have fired 5 times during those 10 minutes, do you run it 5 times or once?"},
        {who:"cand",text:"That's a <strong>policy per job</strong>, and I make it explicit. Some jobs want <strong>catch-up / backfill</strong> — run every missed occurrence (e.g. a billing tick per period) — so on recovery I materialize each missed fire time and execute them, each with its own execution id so they're distinct and idempotent. Others want <strong>skip-to-latest</strong> — a cache-refresh job only needs to run once now, not five stale times — so I collapse missed runs into one. I default to skip-to-latest to avoid a thundering backlog, but let job authors opt into catch-up. Either way nothing is silently dropped; the choice is run-each vs run-latest, both driven off the durable schedule."},
      ],resources:[
        {title:"Cron",url:"https://en.wikipedia.org/wiki/Cron"},
        {title:"Hello Interview — Job Scheduler (recovery)",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
      ]},
      {l:"hard",tag:"failover",q:"Clock skew across schedulers — early or double fires.",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> you run many schedulers on different hosts, and their clocks disagree by a few seconds. One host's clock is fast, so it thinks a job is due before it really is — or during a partition handoff two hosts with skewed clocks both decide a job is due. How do you keep timing correct across a fleet?</span>"},
        {who:"cand",text:"First, don't let wall-clock disagreements cause <strong>double-fires</strong> — that's the serious failure, and it's already prevented by the <strong>atomic conditional claim</strong> plus partition ownership: even if two hosts think a job is due, only one wins the <code>pending &rarr; queued</code> transition, and after a claim <code>next_run_at</code> is advanced so the job isn't due again. So skew can at worst make a job fire slightly early or late, never twice. For timing accuracy I keep hosts synced with <strong>NTP</strong> and treat the store's committed state, not any single host's clock, as the arbiter of what has already been enqueued."},
        {who:"intv",text:"A fast clock still fires a job seconds early. For a job that must not run before its time, how do you bound that?"},
        {who:"cand",text:"I make the <strong>store's authoritative timestamp</strong> the reference rather than the scheduler's local clock — the claim checks due-ness against the database's clock (or a logical time source), so all schedulers agree on now from one source of truth. I can also require that the fire time has passed by the store's clock at claim commit, rejecting a premature claim. For jobs with strict not-before semantics I add a small guard so a few seconds of residual skew errs on the side of firing slightly late, never early. The principle: coordinate timing through a shared authority (the store, NTP-disciplined), and lean on the atomic claim so that even worst-case skew is a small timing error, not a correctness violation."},
      ],resources:[
        {title:"Leader election",url:"https://en.wikipedia.org/wiki/Leader_election"},
        {title:"System Design Primer — consistency patterns",url:"https://github.com/donnemartin/system-design-primer"},
      ]},
    ],
    queue:[
      {l:"medium",tag:"concept",q:"Why a queue between scheduler and workers, and what semantics?",turns:[
        {who:"intv",text:"You put a task queue between the scheduler and the workers. What does it buy you, and what delivery semantics do you configure?"},
        {who:"cand",text:"It <strong>decouples dispatch from execution</strong> and gives me durability across the handoff. The scheduler enqueues a due job and moves on; workers consume independently, so neither blocks the other and a worker slowdown just grows queue depth. I configure <strong>at-least-once delivery with a visibility timeout</strong>: a dequeued message is leased (invisible) until the worker acks, and re-delivered if the worker dies.<span class='eg'>enqueue task, worker leases with 60s visibility, acks on success to delete; no ack &rarr; redelivery.</span>The message itself is durable, so a task that's been enqueued survives even if all workers restart."},
        {who:"intv",text:"Kafka-style log or a classic message queue like SQS/RabbitMQ — which and why?"},
        {who:"cand",text:"For this workload I lean toward a queue with <strong>per-message ack and visibility timeout</strong> (SQS/RabbitMQ-style) because tasks are independent units I want to lease, ack, and redeliver individually, with easy dead-lettering — a log's per-partition offset model makes per-message redelivery and out-of-order completion awkward. A <strong>Kafka-style log</strong> shines when I want high-throughput ordered streams and replay, which is more useful for the change/event stream feeding monitoring than for the task-dispatch path. So: message-queue semantics for task dispatch, log semantics where I want durable ordered replay. The deciding factor is that dispatch needs independent per-task lease/ack, not ordering."},
      ],resources:[
        {title:"Kafka documentation",url:"https://kafka.apache.org/documentation/"},
        {title:"System Design Primer — asynchronism",url:"https://github.com/donnemartin/system-design-primer"},
      ]},
      {l:"hard",tag:"scaling",q:"Queue depth explodes at a spike — backpressure without loss.",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> a midnight herd enqueues <b>1M</b> tasks in a couple of minutes but workers can only drain <b>10K/s</b>. Queue depth balloons to hundreds of thousands. How do you keep the queue healthy and not lose tasks?</span>"},
        {who:"cand",text:"A deep queue is the system <em>working as designed</em> — the queue exists to absorb exactly this. Tasks are durable in the queue, so nothing is lost; they just wait. I <strong>autoscale workers on queue depth</strong> to drain faster, and I <strong>partition the queue</strong> so throughput scales horizontally rather than bottlenecking on one broker. The buffer converts an unbounded arrival spike into a bounded, drainable backlog — depth grows, then shrinks, and no work is dropped. The number I care about is drain time, which I keep within jobs' timeliness tolerance by scaling the pool."},
        {who:"intv",text:"If arrival keeps outpacing drain and depth grows without bound, memory or storage runs out. What then?"},
        {who:"cand",text:"I apply <strong>backpressure upstream</strong> rather than letting the queue collapse. The scheduler watches queue depth and, past a threshold, <strong>slows enqueueing of low-priority jobs</strong> — they stay <code>pending</code> in the durable store (their next_run_at simply passes and they're picked up when depth recovers) instead of piling into the queue. Priority partitions ensure urgent jobs still flow while best-effort ones wait. Because the durable store, not the queue, is the source of truth for due-ness, holding jobs back is safe — they're not lost, just deferred. So the queue has a bounded working set and the durable store holds the long tail, and backpressure ripples from the scarce resource (workers) outward."},
      ],resources:[
        {title:"System Design Primer — asynchronism & backpressure",url:"https://github.com/donnemartin/system-design-primer"},
        {title:"ByteByteGo",url:"https://bytebytego.com/"},
      ]},
      {l:"hard",tag:"durability",q:"The queue loses in-flight tasks on a broker failure.",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> a queue broker node fails while holding <b>200K</b> enqueued-but-unprocessed tasks. If those messages were only in that node's memory, they're gone — 200K scheduled executions silently vanish. How do you make the queue itself durable?</span>"},
        {who:"cand",text:"Enqueued tasks must be <strong>durably persisted and replicated</strong> before the enqueue is considered done — the queue writes each message to disk and replicates to multiple brokers with quorum ack, so a single broker failure loses nothing and a replica takes over with the full backlog. But there's a stronger backstop specific to this system: the <strong>durable job store is the real source of truth</strong>. The queue is a dispatch buffer, not the record of what needs to run. So even if the queue lost messages, those jobs are still <code>queued</code>/<code>pending</code> in the store with a next_run_at, and the scheduler's overdue scan re-enqueues them."},
        {who:"intv",text:"So the queue is allowed to lose messages because the store can rebuild them? Isn't that wasteful reconciliation?"},
        {who:"cand",text:"I don't <em>rely</em> on it as the primary mechanism — I use a replicated, durable queue so message loss is rare. But designing the store as the authority makes the queue loss <strong>recoverable rather than catastrophic</strong>, which is the property I want for a durability-critical system. A job that was enqueued but whose queue message vanished shows up in the overdue scan (its state and next_run_at persisted) and gets re-dispatched — late, not lost. The reconciliation is cheap because it's the same scan the scheduler already runs. Defense in depth: durable queue as the fast path, durable store as the guarantee that no scheduled execution can ever truly disappear."},
      ],resources:[
        {title:"Kafka documentation — replication & durability",url:"https://kafka.apache.org/documentation/"},
        {title:"Hello Interview — Job Scheduler (durability)",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
      ]},
    ],
    coordinator:[
      {l:"medium",tag:"concept",q:"What does the coordinator do — leader election and assignment?",turns:[
        {who:"intv",text:"You added a coordinator for leader election and locks. Concretely, what does it manage and how do schedulers use it?"},
        {who:"cand",text:"It's the arbiter of <strong>who is allowed to act</strong>. Using <strong>ZooKeeper or etcd</strong>, it manages two things: <strong>membership</strong> (which scheduler instances are alive, via ephemeral nodes / leases with heartbeats) and <strong>partition assignment</strong> (which instance owns which slice of the job space). Schedulers register, receive their partitions, and renew a lease; if one dies its lease expires and the coordinator reassigns its partitions to survivors.<span class='eg'>ZooKeeper ephemeral znodes: a scheduler's node vanishes when its session drops, triggering a rebalance watched by the others.</span>It gives me both no-SPOF failover and disjoint ownership so nothing double-fires."},
        {who:"intv",text:"Why not have schedulers coordinate peer-to-peer instead of depending on a coordinator?"},
        {who:"cand",text:"Peer-to-peer consensus is exactly what ZooKeeper/etcd already solve correctly — reinventing distributed agreement (who's the leader, who owns what) in application code is a classic source of split-brain bugs. Delegating to a battle-tested consensus system gives me <strong>linearizable membership and assignment</strong> with fencing built in. My schedulers stay simple: they ask the coordinator who owns what and act only within their assignment. The coordinator is small and rarely on the hot path (it's consulted on membership changes, not every job), so it's a reliability asset, not a bottleneck."},
      ],resources:[
        {title:"ZooKeeper overview",url:"https://zookeeper.apache.org/doc/current/zookeeperOver.html"},
        {title:"Leader election",url:"https://en.wikipedia.org/wiki/Leader_election"},
      ]},
      {l:"medium",tag:"scaling",q:"Rebalancing partitions as schedulers come and go.",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> you scale from 4 to <b>40</b> schedulers during a busy period, and nodes churn — some crash, some are added. Partitions must be reassigned each time. How do you rebalance without either overloading the coordinator or dropping coverage of some jobs?</span>"},
        {who:"cand",text:"Use <strong>consistent hashing</strong> for partition-to-scheduler assignment so adding or removing a node only moves a small fraction of partitions, not a full reshuffle — churn is cheap and rebalances are incremental. The coordinator only stores the assignment map and membership, which is tiny metadata, so it isn't stressed by the churn itself. Each partition always has exactly one owner in the map, so there's never a gap where some jobs are unscanned; a reassigned partition transfers ownership atomically from old to new owner."},
        {who:"intv",text:"During the moment of handoff, could a partition be owned by nobody (jobs unscanned) or by two (double-scan)?"},
        {who:"cand",text:"Both risks exist in the transition window, and I handle them opposite ways. <strong>Briefly unowned</strong> is acceptable — jobs in that partition just wait a second and are picked up by the overdue scan when the new owner takes over, so it's a small timeliness blip. <strong>Briefly double-owned</strong> is the dangerous one, so I fence it: assignments carry a <strong>fencing token / epoch</strong>, and the atomic per-job claim rejects a stale owner's writes. So the safe failure (a gap) is tolerated because the durable store makes it recoverable, and the unsafe failure (overlap) is prevented by fencing. I bias every ambiguous handoff toward not-double-firing."},
      ],resources:[
        {title:"System Design Primer — consistent hashing",url:"https://github.com/donnemartin/system-design-primer"},
        {title:"ZooKeeper overview",url:"https://zookeeper.apache.org/doc/current/zookeeperOver.html"},
      ]},
      {l:"hard",tag:"failover",q:"Split-brain — two schedulers believe they own a partition.",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> a network partition isolates a scheduler from the coordinator. The coordinator declares it dead and reassigns its partitions to another node. But the isolated scheduler is still running and still thinks it owns those partitions. For a few seconds two schedulers scan and enqueue the same jobs. Prevent the double-execution.</span>"},
        {who:"cand",text:"This is the textbook <strong>split-brain</strong>, and the fix is <strong>fencing tokens</strong>. Every partition assignment carries a monotonically increasing token. When the coordinator reassigns the partition to the new owner, it issues a <em>higher</em> token. The job store (and queue) record the highest token seen per partition and <strong>reject any enqueue/claim bearing a lower token</strong>. So the isolated old owner, still holding a stale token, has all its writes fenced off the instant the new owner acts — it literally cannot enqueue, even though it believes it still owns the partition. Liveness comes from reassignment; safety comes from fencing."},
        {who:"intv",text:"The old scheduler may have <em>already</em> enqueued job 42 before the new owner got the higher token. Now the task is in the queue twice. Still safe?"},
        {who:"cand",text:"Yes, because I don't rely on fencing alone — the <strong>atomic per-job claim</strong> is the second layer. Enqueue is gated by the conditional transition <code>pending &rarr; queued</code> plus advancing <code>next_run_at</code>; only one enqueue per fire time can win that transition, so even racing owners can't both enqueue job 42 for the same occurrence. And if somehow two task messages did exist, the final backstop is <strong>idempotent execution</strong> keyed on the execution id — the second run is a no-op at the side-effecting boundary. Three layers: fencing tokens (stop the stale owner), atomic claim (one enqueue per fire time), idempotency (harmless duplicate execution). Defense in depth is deliberate because a double-fire on a billing job is unacceptable."},
      ],resources:[
        {title:"Leader election",url:"https://en.wikipedia.org/wiki/Leader_election"},
        {title:"ZooKeeper overview",url:"https://zookeeper.apache.org/doc/current/zookeeperOver.html"},
      ]},
    ],
    deadletter:[
      {l:"medium",tag:"concept",q:"What goes to the dead-letter, and why separate it?",turns:[
        {who:"intv",text:"You route exhausted jobs to a dead-letter store. What exactly lands there, and why is a separate store better than just leaving them failed?"},
        {who:"cand",text:"A job lands in the dead-letter after it has <strong>exhausted its retry budget</strong> — say 5 attempts with backoff all failed — carrying the job def, payload, execution id, attempt count, and the <strong>last error(s)</strong> for diagnosis.<span class='eg'>a job calling a downstream that's been 500ing all day burns its retries, then dead-letters with the captured error rather than retrying forever.</span>Separating it gives me an explicit, <strong>monitorable surface</strong>: I alert on dead-letter depth, operators triage poison jobs, and I keep permanently-failing work out of the hot retry path so it can't waste worker capacity spinning."},
        {who:"intv",text:"How do you distinguish a poison job (bad input, will never succeed) from a job that failed due to a transient outage?"},
        {who:"cand",text:"The retry policy is the filter. <strong>Transient</strong> failures (timeouts, 503s, connection resets) are retried with backoff and usually succeed within the budget, so they never reach the dead-letter. What survives all retries is likely a <strong>poison job</strong> — bad payload, a permanent downstream error (400, auth failure), or a code bug. I can classify further using the error type: retry on 5xx/timeouts, fail-fast to dead-letter on 4xx/validation errors since retrying won't help. So the dead-letter accumulates genuinely stuck work, and its depth becomes a meaningful signal rather than noise from transient blips."},
      ],resources:[
        {title:"Hello Interview — Job Scheduler (retries & dead-letter)",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
        {title:"System Design Primer — reliability",url:"https://github.com/donnemartin/system-design-primer"},
      ]},
      {l:"medium",tag:"scaling",q:"A bad deploy dead-letters a flood of jobs at once.",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> a broken deploy on a popular downstream makes <b>50K</b> jobs fail their retries within an hour, all pouring into the dead-letter store. It must absorb that flood, and later you need to replay all 50K once the downstream is fixed. How do you handle the volume both ways?</span>"},
        {who:"cand",text:"The dead-letter is just another <strong>durable, append-friendly store</strong>, so absorbing 50K entries is a non-issue — it's sized for writes and I partition it if needed. The bigger design point is that a flood into the dead-letter is a <strong>signal</strong>: a sharp spike in its depth should page someone, because it usually means a systemic downstream failure, not 50K independent bad jobs. That alerting turns the dead-letter into an early-warning system for exactly this kind of bad-deploy blast radius."},
        {who:"intv",text:"Now replay all 50K after the fix. How do you do that without re-creating the same overload?"},
        {who:"cand",text:"Replay is a <strong>controlled, rate-limited re-enqueue</strong>, not a dump. I feed the 50K back through the normal scheduler/queue path at a throttled rate so I don't instantly re-overwhelm the just-recovered downstream — the same backpressure discipline as any herd. Each replayed job keeps its <strong>execution id</strong>, so idempotency still protects any that partially succeeded before failing. I can replay selectively (filter by error type or time window) and dry-run first. So replay reuses the existing dispatch machinery with a throttle, converting a big backlog into a paced drain rather than a second thundering herd."},
      ],resources:[
        {title:"System Design Primer — reliability & queues",url:"https://github.com/donnemartin/system-design-primer"},
        {title:"ByteByteGo",url:"https://bytebytego.com/"},
      ]},
      {l:"hard",tag:"durability",q:"Dead-lettered jobs must never be lost during replay.",turns:[
        {who:"intv",text:"<span class='scenario'><b>Scenario:</b> you're replaying <b>10K</b> dead-lettered jobs and the replay worker crashes halfway. Some were re-enqueued, some weren't, and you're unsure which. If you're careless you either lose the un-replayed ones or double-replay the done ones. Make replay safe.</span>"},
        {who:"cand",text:"I treat replay as a <strong>durable, resumable operation</strong>, not a fire-and-forget loop. Each dead-letter entry has a <strong>replay state</strong> (pending &rarr; replayed) that I transition <em>atomically</em> as I re-enqueue it, so on a crash I know exactly which are done. A restarted replay worker simply resumes over entries still in <code>pending</code> — no loss, because un-replayed entries remain durably in the dead-letter, and no duplication, because replayed ones are already marked. The dead-letter store's durability (replicated, quorum-acked) means an entry never disappears whether or not it's been replayed yet."},
        {who:"intv",text:"A job re-enqueued during replay gets processed, but the crash happened right after enqueue and before you marked it replayed. On resume you re-enqueue it. Double-run?"},
        {who:"cand",text:"That window exists, and it's handled by the same guarantee the whole system leans on: <strong>at-least-once plus idempotency</strong>. A re-enqueue of an already-processed job carries the same <strong>execution id</strong>, so the downstream dedups it and the effect happens once regardless of a double-enqueue. So the marking-after-enqueue gap can at worst cause a harmless duplicate delivery, never a wrong effect. I keep replay <strong>idempotent end to end</strong> precisely so I never have to make enqueue-and-mark atomic across two systems — which, as with execution, isn't truly achievable. Durable replay state prevents loss; idempotency neutralizes the duplicate."},
      ],resources:[
        {title:"Idempotence",url:"https://en.wikipedia.org/wiki/Idempotence"},
        {title:"Hello Interview — Job Scheduler (dead-letter & replay)",url:"https://www.hellointerview.com/learn/system-design/problem-breakdowns/job-scheduler"},
      ]},
    ],
  }
};
